apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homepage

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

configMapGenerator:
  - name: homepage-html
    files:
    - html/index.html
  - name: nginx-autoindex-conf
    files:
    - nginx/autoindex.conf
